name: Create Branch
on: 
  workflow_dispatch:

jobs:
  branchSweeper:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/github-script@e69ef5462fd455e02edcaf4dd7708eda96b9eda0 # v7.0.0
        with:
          script: |
                async function createBranch(){
                  let dateToday = new Date().toJSON().slice(0, 10);

                  const masterRef = await github.rest.git.getRef({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    ref: "heads/master"
                  })
                  const branchName = "UTC-nightly-tests-" + dateToday;
                   const resp = await github.rest.git.createRef({
                     owner: context.repo.owner,
                     repo: context.repo.repo,
                     ref: "refs/heads/" + branchName,
                     sha: masterRef.data.object.sha
                   })
                   console.log("Created Branch: " + branchName)
                }

                createBranch()