name: Dependency Setup
on: 
  workflow_call:
    inputs:
      cache-key:
        description: 'the key for the poetry cache'
        default: ''
        required: true
        type: string

jobs:
  python:
     runs-on: ubuntu-20.04
     steps:
     - uses: actions/checkout@v4
     - run: ls && pwd
     - name: Install poetry
       run: pipx install poetry
     - uses: actions/setup-python@v5
       with:
        python-version: '3.9'
     - name: Load cached venv
       id: cached-poetry-dependencies
       uses: actions/cache@v3
       with:
        path: ./temp
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-
     - name: Install poetry
       if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
       run: poetry install
     - run: poetry run python hello.py