name: Hello World
on:
  pull_request
  push
  workflow_run:
    workflows: Dependency Setup
    types: completed


jobs:
  hello-job:
    name: Preflight Step
    runs-on: ubuntu-latest
    steps:
      - run: poetry run python hello.py