name: Hello World
on: workflow_dispatch


jobs:
  dependency-transfer:
    uses: ./.github/workflows/dependency_setup.yaml
    with:
      cache-key: "mau"
  hello-job:
    name: Preflight Step
    runs-on: ubuntu-latest
    needs: ["dependency-transfer"]
    steps:
    - run: poetry run python hello.py