name: Hello World
on: workflow_dispatch


jobs:
  dependency-transfer:
    uses: ./.github/workflows/dependency_setup.yaml
    with:
      cache-key: "mau"

  cache-restore:
    name: cache restore
    runs-on: ubuntu-latest
    needs: ["dependency-transfer"]
    steps:
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
       path: temp
       key: ${{ runner.os }}-mau
  hello-job-1:
    name: Preflight Step
    runs-on: ubuntu-latest
    needs: ["cache-restore"]
    steps:
    - run: poetry run python hello.py
  hello-job-2:
    name: Preflight Step
    runs-on: ubuntu-latest
    needs: ["cache-restore"]
    steps:
    - run: poetry run python hello.py
  hello-job-3:
    name: Preflight Step
    runs-on: ubuntu-latest
    needs: ["cache-restore"]
    steps:
    - run: poetry run python hello.py